export const dashboardNav = [
  {
    href: "/dashboard",
    label: "Overview",
    description: "Workspace health",
    icon: "LayoutDashboard",
  },
  {
    href: "/dashboard/agents",
    label: "Agents",
    description: "Manage autonomous agents",
    icon: "Bot",
  },
  {
    href: "/dashboard/activity",
    label: "Activity",
    description: "Execution timeline",
    icon: "Activity",
  },
  {
    href: "/dashboard/workflows",
    label: "Workflows",
    description: "Builder and schedules",
    icon: "GitBranch",
  },
  {
    href: "/dashboard/releases",
    label: "Releases",
    description: "Canary rollout control",
    icon: "Rocket",
  },
  {
    href: "/dashboard/tools",
    label: "Tools",
    description: "Marketplace and installs",
    icon: "Wrench",
  },
  {
    href: "/dashboard/reliability",
    label: "Reliability",
    description: "Agent trust scorecards",
    icon: "ShieldCheck",
  },
  {
    href: "/dashboard/impact",
    label: "Impact",
    description: "Business value metrics",
    icon: "TrendingUp",
  },
  {
    href: "/dashboard/knowledge",
    label: "Knowledge",
    description: "Cross-agent learning graph",
    icon: "Brain",
  },
  {
    href: "/dashboard/intelligence",
    label: "Intelligence",
    description: "Competitive nerve center",
    icon: "Zap",
  },
  {
    href: "/dashboard/control-plane",
    label: "Control Plane",
    description: "Approvals and live controls",
    icon: "SlidersHorizontal",
  },
  {
    href: "/dashboard/copilot",
    label: "Co-Pilot",
    description: "Human-in-the-loop sessions",
    icon: "Users",
  },
  {
    href: "/dashboard/mission-control",
    label: "Mission Control",
    description: "Fleet ops and incidents",
    icon: "Radar",
  },
  {
    href: "/marketplace",
    label: "OperonHub",
    description: "Workflow marketplace",
    icon: "Store",
  },
  {
    href: "/pipelines",
    label: "Pipelines",
    description: "Multi-agent orchestration",
    icon: "Network",
  },
  {
    href: "/dashboard/autopilot",
    label: "Autopilot",
    description: "Learn and self-repair workflows",
    icon: "Cpu",
  },
  {
    href: "/dashboard/billing",
    label: "Billing",
    description: "Plans and quota",
    icon: "CreditCard",
  },
  {
    href: "/dashboard/finops",
    label: "FinOps",
    description: "Agent cost intelligence",
    icon: "DollarSign",
  },
  {
    href: "/dashboard/security",
    label: "Security",
    description: "Operational guardrails",
    icon: "Lock",
  },
  {
    href: "/sandbox",
    label: "Sandbox",
    description: "Isolated identity economy",
    icon: "FlaskConical",
  },
  {
    href: "/dashboard/shield",
    label: "Shield",
    description: "Prompt injection defense",
    icon: "ShieldAlert",
  },
  {
    href: "/dashboard/compliance",
    label: "Compliance",
    description: "Approvals and passport audit",
    icon: "ClipboardCheck",
  },
  {
    href: "/dashboard/incidents",
    label: "Incidents",
    description: "SLA breach response",
    icon: "AlertTriangle",
  },
] as const;
