import { DashboardCard } from "@/components/dashboard/layout/dashboard-card";
import { SectionHeading } from "@/components/ui/section-heading";
import { ImpactSummary } from "@/components/dashboard/impact/impact-summary";
import { requireOrganizationRole } from "@/server/auth/authorization";
import { calculateMonthlyImpact } from "@/lib/businessImpact/impact.service";

export default async function DashboardImpactPage(): Promise<JSX.Element> {
  const user = await requireOrganizationRole("MEMBER");
  const impact = await calculateMonthlyImpact(user.organizationId!);

  return (
    <div className="space-y-5">
      <SectionHeading
        eyebrow="Business Impact"
        title="ROI and Value Dashboard"
        description="Operational value generated by autonomous workflow runs."
      />
      <DashboardCard>
        <ImpactSummary
          totalROI={impact.totalROI}
          totalRuns={impact.totalRuns}
          totalSavings={impact.totalSavings}
          totalRevenueProtected={impact.totalRevenueProtected}
          workflows={impact.workflows}
        />
      </DashboardCard>
    </div>
  );
}
